version: "3.7"

services:
  backend:
    restart: unless-stopped
    container_name: backend
    image: docker.pkg.github.com/paulords95/serverapioracle/serverapioracle:latest
    networks:
      - public
    volumes:
      - ./Wallet_dev:/opt/oracle/instantclient_19_6/network/admin
      - ./.env:/home/.env
    ports:
      - 5000:5000

networks:
  public:
