name: Deploy
on: [workflow_dispatch]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no opc@$SERVER_IP "ls"
